/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tap_u3proyectofinaldali.documentos;

import com.mycompany.domain.Participante;
import java.util.Base64;
import javax.swing.ImageIcon;

/**
 *
 * @author charl
 */
public class PanelParticipante extends javax.swing.JPanel {

    private Participante participante;

    /**
     * Creates new form PanelParticipante
     */
    public PanelParticipante() {
        initComponents();
    }

    public PanelParticipante(Participante participante) {
        initComponents();
        this.participante = participante;
        initDatos();
    }

    private void initDatos() {
        this.labelNombre.setText(this.participante.getNombre());
        this.labelCarrera.setText(this.participante.getCarrera());
        this.labelNumControl.setText(this.participante.getNumero_control());

        String foto64 = Base64.getEncoder().encodeToString(participante.getFoto());
        
        if (!foto64.isEmpty()) {
            this.panelFoto.setIcon(new ImageIcon(this.participante.getFoto()));
        }

        this.panelFoto.revalidate();
        this.panelFoto.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFoto = new org.edisoncor.gui.panel.PanelImage();
        labelNombre = new javax.swing.JLabel();
        labelNumControl = new javax.swing.JLabel();
        labelCarrera = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new org.edisoncor.gui.util.DropShadowBorder());

        panelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image-PerfilParticipante.png"))); // NOI18N

        javax.swing.GroupLayout panelFotoLayout = new javax.swing.GroupLayout(panelFoto);
        panelFoto.setLayout(panelFotoLayout);
        panelFotoLayout.setHorizontalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelFotoLayout.setVerticalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        labelNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(0, 0, 0));
        labelNombre.setText("Nombre participante");

        labelNumControl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNumControl.setForeground(new java.awt.Color(255, 0, 255));
        labelNumControl.setText("Carrera");

        labelCarrera.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelCarrera.setForeground(new java.awt.Color(255, 0, 255));
        labelCarrera.setText("Carrera");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelCarrera;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumControl;
    private org.edisoncor.gui.panel.PanelImage panelFoto;
    // End of variables declaration//GEN-END:variables
}
