/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tap_u3proyectofinaldali.documentos;

import com.mycompany.data.WSManager;
import com.mycompany.domain.Director;
import com.mycompany.domain.Evento;
import com.mycompany.domain.Participante;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import org.json.simple.parser.ParseException;

/**
 *
 * @author charl
 */
public class PanelEvento extends javax.swing.JPanel {
    
    private Evento evento;
    private Director director;
    private WSManager ws;
    
    private ArrayList<Participante> participants;
    
    /**
     * Creates new form PanelEvento
     */
    public PanelEvento() {
        initComponents();
    }
    
    public PanelEvento(Evento evento, Director director) {
        initComponents();
        this.evento = evento;
        this.director = director;
        this.ws = new WSManager();
        
        try {
            this.participants = this.ws.showParticipants(null);
            
            if (this.participants == null) {
                JOptionPane.showMessageDialog(null, "Error al leer los participantes");
            }
        } catch (IOException ex) {
            Logger.getLogger(PanelEvento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(PanelEvento.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initDatos();
    }
    
    private void initDatos(){
        this.labelFecha.setText(this.evento.getFecha().toString());
        this.labelHora.setText(this.evento.getHora().toString());
        this.labelNombreEvento.setText(this.evento.getNombre());
        
        if (this.evento.isValidado()) {
            this.itemStatus.setForeground(Color.GREEN);
            this.itemStatus.setText(String.format("""
                                    Evento validado por
                                    el Director %s
                                    """, this.director.getNombre()));
        } else {
            this.itemStatus.setForeground(Color.red);
            this.itemStatus.setText("Evento sin validar");
        }
        
        // Creamos todos los items para el menu participantes
        for (Participante participant : participants) {
            JMenuItem item = new JMenuItem(participant.getNombre());
            this.menuParticipantes.add(item);
        }
        this.menuParticipantes.revalidate();
        this.menuParticipantes.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        itemStatus = new javax.swing.JMenuItem();
        menuParticipantes = new javax.swing.JPopupMenu();
        itemAddParticipants = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        buttonEliminar = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        labelNombreEvento = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        buttonStatus = new javax.swing.JButton();
        buttonParticipantes = new javax.swing.JButton();

        itemStatus.setForeground(new java.awt.Color(255, 0, 0));
        itemStatus.setText("Sin validar");
        jPopupMenu1.add(itemStatus);

        itemAddParticipants.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemAddParticipants.setForeground(new java.awt.Color(255, 0, 255));
        itemAddParticipants.setText("Agregar participantes");
        itemAddParticipants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddParticipantsActionPerformed(evt);
            }
        });
        menuParticipantes.add(itemAddParticipants);
        menuParticipantes.add(jSeparator1);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new org.edisoncor.gui.util.DropShadowBorder());

        buttonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        buttonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-Editar.png"))); // NOI18N
        buttonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelNombreEvento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNombreEvento.setForeground(new java.awt.Color(0, 0, 0));
        labelNombreEvento.setText("Nombre del evento");

        labelFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 51, 255));
        labelFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelFecha.setText("Fecha");

        labelHora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelHora.setForeground(new java.awt.Color(255, 51, 255));
        labelHora.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelHora.setText("Hora");

        buttonStatus.setText("Status");
        buttonStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonStatusMouseClicked(evt);
            }
        });

        buttonParticipantes.setText("Participantes");
        buttonParticipantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonParticipantesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombreEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(buttonParticipantes)
                .addGap(18, 18, 18)
                .addComponent(buttonStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelNombreEvento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFecha)
                    .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonParticipantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void buttonStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonStatusMouseClicked
        this.jPopupMenu1.show(this.buttonStatus, WIDTH, this.buttonStatus.getHeight());
    }//GEN-LAST:event_buttonStatusMouseClicked

    private void buttonParticipantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonParticipantesMouseClicked
        this.menuParticipantes.show(this.buttonParticipantes, WIDTH, this.buttonParticipantes.getHeight());
    }//GEN-LAST:event_buttonParticipantesMouseClicked

    private void itemAddParticipantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddParticipantsActionPerformed
        new CargarParticipantesForm(this.evento).setVisible(true);
    }//GEN-LAST:event_itemAddParticipantsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonParticipantes;
    private javax.swing.JButton buttonStatus;
    private javax.swing.JMenuItem itemAddParticipants;
    private javax.swing.JMenuItem itemStatus;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelNombreEvento;
    private javax.swing.JPopupMenu menuParticipantes;
    // End of variables declaration//GEN-END:variables
}
